version: "3.9"

services:
  app:
    build:
      context: .
    environment:
      ORACLE_USER: "SYS"
      ORACLE_PASSWORD: "example"
      ORACLE_SCHEMA: "CLUB"
      ORACLE_URL: "oracle:1521/xepdb1"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "example"
      MYSQL_DATABSE: "service"
      MYSQL_HOST: "mysql"
      TABID: 99999

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

    ports:
      - 3306:3306

  oracle:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
      ORACLE_PASSWORD: example